# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1fe88d76d7817f762b48e19314d37052ef4d1a772a731ff6ac715f36cde8f7a14c6c89693134ee81e4b6277d2e1ec58aba3cce1ebe6efa30d0b5433a904fb1e

test:
  secret_key_base: 62561188ec2414e8b1b42b50de064aada9226945d9e219d3df4442536bbbd572f4b49c25a9f7174484d3c31c38f1425073015face7f666dbf509ef027073f4fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
